[global]
respect-gitignore = true
include = [
    "README.md",
    "benchmark/README.md",
]
exclude = [
    ".git/",
    ".github/",
]
disable = []

[MD013]
line-length = 100
code-blocks = false

[MD033]
allowed-elements = [
    "no-markdown-equivalent",
    "img", "p", "a",
]