[package]
name = "uuid7-rs"
version = "0.0.9"
edition = "2024"
build = "build.rs"

[lib]
name = "_core"
crate-type = ["cdylib"]

# [build-dependencies]
# pyo3-build-config = { version = "=0.29.0", features = ["resolve-config"] }
[build-dependencies.pyo3-build-config]
git = "https://github.com/PyO3/pyo3"
rev = "f7f74cfd1133b6d8415f79f34d41587ad1ca8466"

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
rev = "f7f74cfd1133b6d8415f79f34d41587ad1ca8466"
# remove after pyo3 0.29.0 release
features = ["generate-import-lib"]

[target."cfg(windows)".dependencies]
windows-link = "=0.2.1"

[dependencies.rand]
version = "=0.10.1"
default-features = false
features = [
    "std_rng",
    "sys_rng",
]

[dependencies.mimalloc]
optional = true
version = "=0.1.52"
features = [
    "override",
    "local_dynamic_tls",
]

[features]
default = []
mimalloc = ["dep:mimalloc"]

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
strip = "symbols"
codegen-units = 1

[lints.rust]
warnings = "deny"

[lints.clippy]
perf = { level = "deny", priority = 1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }

allow_attributes = "deny"
disallowed_types = "deny"

too_many_lines = "allow"
manual_let_else = "allow"
cast_possible_truncation = "allow"
missing_const_for_fn = "allow"
similar_names = "allow"