[package]
name = "uuid7-rs"
version = "0.0.7"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib"]

# [build-dependencies]
# pyo3-build-config = { version = "=0.29.0", features = ["resolve-config"] }
[build-dependencies.pyo3-build-config]
git = "https://github.com/PyO3/pyo3"
rev = "20246a895718baa603f836b187b498cedc6941ca"
features = ["resolve-config"]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
rev = "20246a895718baa603f836b187b498cedc6941ca"
# remove after pyo3 0.29.0 release
features = ["generate-import-lib"]

[target."cfg(unix)".dependencies]
libc = "=0.2.186"

[dependencies.rand]
version = "=0.10.1"
default-features = false
features = [
    "std_rng",
    "sys_rng",
]

[dependencies.mimalloc]
optional = true
version = "=0.1.50"
features = [
    "override",
    "local_dynamic_tls",
]

[features]
default = []
mimalloc = ["dep:mimalloc"]

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
strip = "symbols"
codegen-units = 1

[lints.rust]
warnings = "deny"

[lints.clippy]
perf = { level = "deny", priority = 1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }

allow_attributes = "deny"
disallowed_types = "deny"

too_many_lines = "allow"
manual_let_else = "allow"
cast_possible_truncation = "allow"
missing_const_for_fn = "allow"
