[build-system]
requires = ["maturin == 1.13.3"]
build-backend = "maturin"

[tool.maturin]
python-source = "py-src"
module-name = "uuid7_rs._core"

[project]
name = "uuid7-rs"
dynamic = ["version"]
requires-python = ">=3.10"
description = "Fast UUID v7 generator written in Rust"
readme = "README.md"
license = "Unlicense"
license-files = ["UNLICENSE"]
authors = [
    { name = "chirizxc", email = "chirizxc@proton.me" }
]
classifiers = [
    "Typing :: Typed",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries",
]
urls.Source = "https://github.com/lava-sh/uuid7-rs"
urls.Homepage = "https://github.com/lava-sh/uuid7-rs"
urls."Bug Tracker" = "https://github.com/lava-sh/uuid7-rs/issues"

[dependency-groups]
typos = ["typos == 1.46.3"]
zizmor = ["zizmor == 1.25.2"]
rumdl = ["rumdl == 0.2.2"]
maturin = ["maturin == 1.13.3"]
pytest = ["pytest == 9.0.3"]
wasm-test = [
    { include-group = "pytest" },
    "pytest-pyodide == 0.59.2",
    "pytest-httpserver == 1.1.5",
]
ci = [
    "ty == 0.0.40",
    "ruff == 0.15.14",
    { include-group = "maturin" },
    { include-group = "pytest" },
]
dev = [
    { include-group = "ci" },
    { include-group = "typos" },
    { include-group = "rumdl" },
    { include-group = "zizmor" },
]
bench = [
    "c_uuid_v7 == 0.0.11",
    "uuid_utils == 0.16.0",
    "uuid_v7 == 1.0.0",
    "UUIDv7gen == 1.0.3",
    "uuid6 == 2025.0.1",
    "lastuuid == 0.5.0",
    "fastuuid == 0.14.0",
    # # # # # # # # # #
    "polars == 1.41.0",
    "altair == 6.1.0",
    "py-cpuinfo == 9.0.0",
    "vl-convert-python == 1.9.0.post1",
]

[tool.uv.dependency-groups]
wasm-test = { requires-python = ">=3.11" }