[build-system]
requires = ["maturin == 1.15.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "py-src"
module-name = "uuid7_rs._core"

[project]
name = "uuid7-rs"
dynamic = ["version"]
requires-python = ">= 3.11"
description = "Fast UUID v7 generator written in Rust"
readme = { file = "README.md", content-type = "text/markdown" }
license = "Unlicense"
license-files = ["UNLICENSE"]
authors = [
    { name = "chirizxc", email = "chirizxc@proton.me" }
]
classifiers = [
    "Typing :: Typed",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries",
    "Development Status :: 5 - Production/Stable",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/lava-sh/uuid7-rs"
Repository = "https://github.com/lava-sh/uuid7-rs"
Issues = "https://github.com/lava-sh/uuid7-rs/issues"

[dependency-groups]
typos = ["typos == 1.50.0"]
zizmor = ["zizmor == 1.29.0"]
rumdl = ["rumdl == 0.2.62"]
maturin = [
    "maturin == 1.15.0 ; sys_platform != 'linux'",
    "maturin[patchelf] == 1.15.0 ; sys_platform == 'linux'",
]
pytest = ["pytest == 9.1.1"]
wasm-test = [
    { include-group = "pytest" },
    "pytest-pyodide == 0.59.2",
    "pytest-httpserver == 1.1.5",
]
ci = [
    "ty == 0.0.75",
    "ruff == 0.16.5",
    { include-group = "maturin" },
    { include-group = "pytest" },
]
dev = [
    { include-group = "ci" },
    { include-group = "typos" },
    { include-group = "rumdl" },
    { include-group = "zizmor" },
]
bench = [
    "uuid_utils",
    "uuid_v7",
    "UUIDv7gen",
    "uuid6",
    "lastuuid",
    "fastuuid",
    "fastuuid7",
    # # # # # # # # # #
    "polars[plot] == 1.44.1",
    "py-cpuinfo2 == 10.1.1",
    "vl-convert-python == 1.9.0.post1",
]

[tool.uv.dependency-groups]
wasm-test = { requires-python = ">= 3.13" }